routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{AdminController, DepartmentController, EmployeeController};

Route::get('/admin', [AdminController::class, 'index'])->name('dashboard');

Route::get('department/{id}/delete', [DepartmentController::class, 'destroy'])->name('department-delete');
Route::resource('department', DepartmentController::class);

Route::get('employee/{id}/delete', [EmployeeController::class, 'destroy'])->name('employee-delete');
Route::resource('employee', EmployeeController::class);



// Route::get('/', function () {
//     return view('welcome');
// });

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    function department()
    {
        return $this->belongsTo(Department::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\{Department, Employee};

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Employee::with('Department')->orderByDesc('id')->get();
        // dd($data);
        return view('pages.admin.employee.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = Department::all();
        return view('pages.admin.employee.create', compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'full_name' => 'required',
            'address' => 'required',
            'department' => 'required',
            'photo' => 'required|image|mimes:jpg,jpeg,png,svg,gif',
            'mobile_number' => 'required',
            'status' => 'required'
        ]);

        $photo = $request->file('photo');
        $renamePhoto = time().'.'.$photo->getClientOriginalExtension();
        $dest = public_path('/images');
        $photo->move($dest, $renamePhoto);

        $data = new Employee;
        $data->full_name = $request->full_name;
        $data->address = $request->address;
        $data->photo = $renamePhoto;
        $data->department_id = $request->department;
        $data->mobile_number = $request->mobile_number;
        $data->status = $request->status;
        $data->save();

        return redirect()->route('employee.create')->with('success', 'data has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Employee::find($id);
        return view('pages.admin.employee.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Employee::find($id);
        $depart = Department::all();
        return view('pages.admin.employee.edit', compact('data', 'depart'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'full_name' => 'required',
            'address' => 'required',
            'department' => 'required',
            'photo' => 'image|mimes:jpg,jpeg,png,svg,gif',
            'mobile_number' => 'required',
            'status' => 'required'
        ]);

        if($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $renamePhoto = time().'.'.$photo->getClientOriginalExtension();
            $dest = public_path('/images');
            $photo->move($dest, $renamePhoto);

            $image_path = 'images/'.$request->prev_photo; 
            // dd($image_path);
            if(\File::exists($image_path)){
                \File::delete($image_path);
            }
        } else {
            $renamePhoto = $request->prev_photo;
        }

    
        $data = Employee::find($id);
        $data->full_name = $request->full_name;
        $data->address = $request->address;
        $data->photo = $renamePhoto;
        $data->department_id = $request->department;
        $data->mobile_number = $request->mobile_number;
        $data->status = $request->status;
        $data->save();

        return redirect()->route('employee.edit', $id)->with('success', 'data has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Employee::where('id', $id)->delete();
        $data = Employee::find($id);
        $data->delete();
        $image_path = 'images/'.$data->photo; 
        // dd($image_path);
        if(\File::exists($image_path)){
            \File::delete($image_path);
        }
        return redirect()->route('employee.index')->with('success', 'data has been deleted');
    }
}

resources/views/pages/admin/employee/create.blade.php
@extends('layouts.admin')
@section('title', 'Create Employee')

@section('content')
    <div class="card mb-4 mt-3 mx-3">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
                Create Employee
            <a href="{{ route('employee.index') }}" class="float-end btn btn-primary btn-sm">View All</a>
        </div>
        <div class="card-body">
            @if(Session::has('success'))
                <p class="text-success">{{ session('success') }}</p>
            @endif

            @if($errors->any())
                @foreach($errors->all() as $error)
                    <p class="text-danger">{{ $error }}</p>
                @endforeach
            @endif

            <form action="{{ route('employee.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <table class="table table-bordered">
                    <tr>
                        <th>Full Name</th>
                        <td>
                            <input type="text" name="full_name" class="form-control" value="{{ old('full_name') }}">
                        </td>
                    </tr>
                    <tr>
                        <th>Department</th>
                        <td>
                            <select name="department" id="department" class="form-control">
                                <option value="">-- Select Departement ---</option>
                                @foreach($data as $d)
                                    <option value="{{ $d->id }}">{{ $d->title }}</option>
                                @endforeach
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <th>photo</th>
                        <td>
                            <input type="file" name="photo" class="form-control">
                        </td>
                    </tr>
                    <tr>
                        <th>Address</th>
                        <td>
                            <input type="text" name="address" class="form-control" value="{{ old('address') }}">
                        </td>
                    </tr>
                    <tr>
                        <th>mobile</th>
                        <td>
                            <input type="text" name="mobile_number" class="form-control" value="{{ old('mobile_number') }}">
                        </td>
                    </tr>
                    <tr>
                        <th>Status</th>
                        <td>
                             <input type="radio" name="status" value="1"> Activate <br>
                             <input type="radio" name="status" value="0" checked="checked"> Deactivate
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <input type="submit" value="submit" class="btn btn-success">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/admin/employee/edit.blade.php
@extends('layouts.admin')
@section('title', 'Update Employee')

@section('content')
    <div class="card mb-4 mt-3 mx-3">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
                Update Employee
            <a href="{{ route('employee.index') }}" class="float-end btn btn-primary btn-sm">View All</a>
        </div>
        <div class="card-body">
            @if(Session::has('success'))
                <p class="text-success">{{ session('success') }}</p>
            @endif

            @if($errors->any())
                @foreach($errors->all() as $error)
                    <p class="text-danger">{{ $error }}</p>
                @endforeach
            @endif

            <form action="{{ route('employee.update', $data->id) }}" method="post" enctype="multipart/form-data">
                @method('put')
                @csrf
                <table class="table table-bordered">
                    <tr>
                        <th>Full Name</th>
                        <td>
                            <input type="text" name="full_name" class="form-control" value="{{ $data->full_name }}">
                        </td>
                    </tr>
                    <tr>
                        <th>Department</th>
                        <td>
                            <select name="department" id="department" class="form-control">
                                <option value="">-- Select Departement ---</option>
                                @foreach($depart as $d)
                                    <option @if ($d->id == $data->department_id) selected @endif value="{{ $d->id }}">{{ $d->title }}</option>
                                @endforeach
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <th>photo</th>
                        <td>
                            <input type="file" name="photo" class="form-control">
                            <p>
                                <img src="{{ asset('images/'.$data->photo) }}" alt="" width="200">
                                <input type="hidden" name="prev_photo" value="{{ $data->photo }}">
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <th>Address</th>
                        <td>
                            <input type="text" name="address" class="form-control" value="{{ $data->address }}">
                        </td>
                    </tr>
                    <tr>
                        <th>mobile</th>
                        <td>
                            <input type="text" name="mobile_number" class="form-control" value="{{ $data->mobile_number }}">
                        </td>
                    </tr>
                    <tr>
                        <th>Status</th>
                        <td>
                             <input type="radio" name="status" value="1" @if($data->status == 1) checked @endif> Activate <br>
                             <input type="radio" name="status" value="0" @if($data->status == 0) checked @endif> Deactivate
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <input type="submit" value="submit" class="btn btn-success">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/admin/employee/index.blade.php
@extends('layouts.admin')
@section('title', 'All Employee')

@section('content')
<div class="card mb-4 mt-3 mx-3">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        All Employee
        <a href="{{ route('employee.create') }}" class="float-end btn btn-primary btn-sm">Add New</a>
    </div>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Department</th>
                    <th>Full Name</th>
                    <th>Photo</th>
                    <th>Address</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>#</th>
                    <th>Department</th>
                    <th>Full Name</th>
                    <th>Photo</th>
                    <th>Address</th>
                    <th>Action</th>
                </tr>
            </tfoot>
            <tbody>
                @if($data)
                    @foreach($data as $key=>$d)
                        <tr>
                            <td style="width: 5%;">{{ $key+1 }}</td>
                            <td style="width: 20%;">{{ $d->department->title }}</td>
                            <td style="width: 20%;">{{ $d->full_name }}</td>
                            <td>
                                <img src="{{ asset('images/'.$d->photo) }}" width="80">
                            </td>
                            <td style="width: 20%;">{{ $d->address }}</td>
                            <td style="width: 20%;">
                                <a href="{{ route('employee.show', $d->id) }}" class="btn btn-sm btn-warning">Show</a>
                                <a href="{{ route('employee.edit', $d->id) }}" class="btn btn-sm btn-primary">Update</a>
                                <a 
                                    href="{{ route('employee-delete', $d->id) }}" 
                                    class="btn btn-sm btn-danger"
                                    onclick="return confirm('are you sure to delete?')">
                                        Delete
                                </a>
                            </td>
                        </tr>
                    @endforeach
                @endif
            </tbody>
        </table>
    </div>
</div>
@endsection

resources/views/pages/admin/employee/show.blade.php
@extends('layouts.admin')
@section('title', 'Show Employee')

@section('content')
    <div class="card mb-4 mt-3 mx-3">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
                Show Employee
            <a href="{{ route('employee.index') }}" class="float-end btn btn-primary btn-sm">View All</a>
        </div>
        <div class="card-body">
            <table class="table table-bordered">
                <tr>
                    <th>Full Name</th>
                    <td>
                        {{ $data->full_name }}
                    </td>
                </tr>
                <tr>
                    <th>Department</th>
                    <td>
                        {{ $data->department->title }}
                    </td>
                </tr>
                <tr>
                    <th>photo</th>
                    <td>
                        <img src="{{ asset('images/'.$data->photo) }}" alt="" width="200">
                    </td>
                </tr>
                <tr>
                    <th>Address</th>
                    <td>
                        {{ $data->address }}
                    </td>
                </tr>
                <tr>
                    <th>mobile</th>
                    <td>
                        {{ $data->mobile_number }}
                    </td>
                </tr>
                <tr>
                    <th>Status</th>
                    <td>
                            @if($data->status == 1) Activated @else Deactivated @endif
                    </td>
                </tr>
            </table>
        </div>
@endsection