routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{AdminController, DepartmentController, EmployeeController};

Route::get('/admin', [AdminController::class, 'index'])->name('dashboard');

Route::get('department/{id}/delete', [DepartmentController::class, 'destroy'])->name('department-delete');
Route::resource('department', DepartmentController::class);

Route::get('employee/{id}/delete', [EmployeeController::class, 'destroy'])->name('employee-delete');
Route::resource('employee', EmployeeController::class);



// Route::get('/', function () {
//     return view('welcome');
// });

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Department;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Department::orderByDesc('id')->get();
        return view('pages.admin.department.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.admin.department.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required'
        ]);

        $data = new Department;
        $data->title = $request->title;
        $data->save();

        return redirect()->route('department.create')->with('success', 'data has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Department::find($id);
        return view('pages.admin.department.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Department::find($id);
        return view('pages.admin.department.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required'
        ]);

        $data = Department::find($id);
        $data->title = $request->title;
        $data->save();

        return redirect()->route('department.edit', $id)->with('success', 'data has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Department::where('id', $id)->delete();
        return redirect()->route('department.index')->with('success', 'data has been deleted');
    }
}

resources/views/pages/admin/department/create.blade.php
@extends('layouts.admin')
@section('title', 'Create department')

@section('content')
    <div class="card mb-4 mt-3 mx-3">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
                Create Department
            <a href="{{ route('department.index') }}" class="float-end btn btn-primary btn-sm">View All</a>
        </div>
        <div class="card-body">
            @if(Session::has('success'))
                <p class="text-success">{{ session('success') }}</p>
            @endif

            @if($errors->any())
                @foreach($errors->all() as $error)
                    <p class="text-danger">{{ $error }}</p>
                @endforeach
            @endif

            <form action="{{ route('department.store') }}" method="post">
                @csrf
                <table class="table table-bordered">
                    <tr>
                        <th>Title</th>
                        <td>
                            <input type="text" name="title" class="form-control">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <input type="submit" value="submit" class="btn btn-success">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/admin/department/edit.blade.php
@extends('layouts.admin')
@section('title', 'Update Department')

@section('content')
    <div class="card mb-4 mt-3 mx-3">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
                Edit Department : <span class="fw-bold">{{ $data->title }}</span> 
            <a href="{{ route('department.index') }}" class="float-end btn btn-primary btn-sm">View All</a>
        </div>
        <div class="card-body">
            @if(Session::has('success'))
                <p class="text-success">{{ session('success') }}</p>
            @endif

            @if($errors->any())
                @foreach($errors->all() as $error)
                    <p class="text-danger">{{ $error }}</p>
                @endforeach
            @endif

            <form action="{{ route('department.update', $data->id) }}" method="post">
                @csrf
                @method('put')
                <table class="table table-bordered">
                    <tr>
                        <th>Title</th>
                        <td>
                            <input type="text" name="title" class="form-control" value="{{ $data->title }}">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <input type="submit" value="Update" class="btn btn-success">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/admin/department/index.blade.php
@extends('layouts.admin')
@section('title', 'All department')

@section('content')
<div class="card mb-4 mt-3 mx-3">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        All Department
        <a href="{{ route('department.create') }}" class="float-end btn btn-primary btn-sm">Add New</a>
    </div>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Action</th>
                </tr>
            </tfoot>
            <tbody>
                @if($data)
                    @foreach($data as $key=>$d)
                        <tr>
                            <td style="width: 5%;">{{ $key+1 }}</td>
                            <td style="width: 75%;">{{ $d->title }}</td>
                            <td style="width: 20%;">
                                <a href="{{ route('department.show', $d->id) }}" class="btn btn-sm btn-warning">Show</a>
                                <a href="{{ route('department.edit', $d->id) }}" class="btn btn-sm btn-primary">Update</a>
                                <a 
                                    href="{{ route('department-delete', $d->id) }}" 
                                    class="btn btn-sm btn-danger"
                                    onclick="return confirm('are you sure to delete?')">
                                        Delete
                                </a>
                            </td>
                        </tr>
                    @endforeach
                @endif
            </tbody>
        </table>
    </div>
</div>
@endsection

resources/views/pages/admin/department/show.blade.php
@extends('layouts.admin')
@section('title', 'Show Department')

@section('content')
    <div class="card mb-4 mt-3 mx-3">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
                Show Department : <span class="fw-bold">{{ $data->title }}</span> 
            <a href="{{ route('department.index') }}" class="float-end btn btn-primary btn-sm">View All</a>
        </div>
        <div class="card-body">
            <table class="table table-bordered">
                <tr>
                    <th>Title</th>
                    <td>
                        {{ $data->title }}
                    </td>
                </tr>
            </table>
        </div>
    </div>
@endsection